spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://172.16.0.157:3307/order
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: yhkj@2020
    slave:
      jdbc-url: jdbc:mysql://172.16.0.157:3308/order
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: slave
      password: slavepass

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-prefix: dao

server.port: 9876